# AcademicPages configuration

# --- Basic Site Settings ---
locale        : "en-US"
title         : "Jiwon Park"
title_separator: "-"
name          : "Jiwon Park"
description   : "Postdoctoral Fellow, Department of Epidemiology, Johns Hopkins University Bloomberg School of Public Health"
url           : "https://jiwonpark41.github.io"
baseurl       : ""
repository    : "JiwonPark41/JiwonPark41.github.io"

# --- Theme ---
remote_theme  : academicpages/academicpages.github.io
site_theme    : "default"   # used by assets/css/main.scss

# --- Plugins (GitHub Pages compatible) ---
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# --- Publication / Talk Category Labels ---
publication_category:
  books:        { title: "Books" }
  manuscripts:  { title: "Journal Articles" }
  conferences:  { title: "Conference Papers" }

talk_category:
  invited:      { title: "Invited Presentations" }
  contributed:  { title: "Contributed Presentations (Talks & Posters)" }

# --- Site Settings ---
teaser         :
breadcrumbs    : false
words_per_minute: 160
future         : true
read_more      : "disabled"
talkmap_link   : false

comments:
  provider     :
  disqus:      { shortname: }
  discourse:   { server: }
  facebook:
    appid     :
    num_posts :
    colorscheme:

staticman:
  allowedFields  : ['name', 'email', 'url', 'message']
  branch         : "gh-pages"
  commitMessage  : "New comment."
  filename       : comment-{@timestamp}
  format         : "yml"
  moderation     : true
  path           : "_data/comments/{options.slug}"
  requiredFields : ['name', 'email', 'message']
  transforms:    { email: "md5" }
  generatedFields:
    date:
      type       : "date"
      options:   { format: "iso8601" }

atom_feed:
  hide         : false
  path         :

# --- SEO / Social ---
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

twitter:   { username: }
facebook:
  username :
  app_id   :
  publisher:

og_image       :
og_description :
social:
  type :
  name :
  links:

# --- Analytics ---
analytics:
  provider     : "false"
  google:      { tracking_id: }

# --- Reading / Excludes ---
include:
  - .htaccess
  - _pages
  - files

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor

keep_files: [".git", ".svn"]
encoding     : "utf-8"
markdown_ext : "markdown,mkdown,mkdn,mkd,md"

# --- Conversion ---
markdown      : kramdown
highlighter   : rouge
lsi           : false
excerpt_separator: "\n\n"
incremental   : false

# --- Kramdown ---
kramdown:
  input       : GFM
  hard_wrap   : false
  auto_ids    : true
  footnote_nr : 1
  entity_output: as_char
  toc_levels  : 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# --- Collections ---
collections:
  teaching:     { output: true, permalink: /:collection/:path/ }
  publications: { output: true, permalink: /:collection/:path/ }
  portfolio:    { output: true, permalink: /:collection/:path/ }
  talks:        { output: true, permalink: /:collection/:path/ }
  pages:        { output: true, permalink: /:path/ }

# --- Defaults ---
defaults:
  - scope: { path: "", type: posts }
    values:
      layout         : single
      author_profile : true
      author         : jiwon
      read_time      : true
      comments       : true
      share          : true
      related        : true
      pagination     : false

  - scope: { path: "", type: pages }
    values:
      layout         : single
      author_profile : true
      author         : jiwon
      pagination     : false

  - scope: { path: "", type: teaching }
    values:
      layout         : single
      author_profile : true
      author         : jiwon
      share          : true
      comments       : true
      pagination     : false

  - scope: { path: "", type: publications }
    values:
      layout         : single
      author_profile : true
      author         : jiwon
      share          : true
      comments       : true
      pagination     : false

  - scope: { path: "", type: portfolio }
    values:
      layout         : single
      author_profile : true
      author         : jiwon
      share          : true
      comments       : true    # ← comment → comments 로 통일
      pagination     : false

  - scope: { path: "", type: talks }
    values:
      layout         : talk
      author_profile : true
      author         : jiwon
      share          : true
      pagination     : false

# --- Sass/SCSS ---
sass:
  sass_dir : _sass
  style    : compressed

# --- Outputting ---
permalink : /:categories/:title/
timezone  : America/New_York

# --- Archives ---
category_archive: { type: liquid, path: /categories/ }
tag_archive     : { type: liquid, path: /tags/ }

# --- HTML Compression ---
compress_html:
  clippings: all
  ignore: { envs: development }
